swagger: "2.0"
info:
  title: Bank Argent API transaction
  description: Transaction API
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - transaction module
      summary: Transaction Month API
      description: API for fetching month transactions
      parameters:
        - in: header
          name: Authorization
          description: Attach bearer JWT token
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: User transactions retrieved successfully
          schema:
            $ref: "#/definitions/allTransactionsResponse"
        "400":
          description: Invalid Fields
        "404":
          description: Transactions not found
        "500":
          description: Internal server error

  /user/transactions/{idTransaction}:
    get:
      security:
        - Bearer: []
      tags:
        - transaction module
      summary: Transaction show API
      description: API for showing a transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach bearer JWT token
          required: true
          type: string
        - in: path
          name: idTransaction
          description: ID of transaction
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: Transaction retrieved successfully
          schema:
            $ref: "#/definitions/transactionResponse"
        "400":
          description: Invalid Fields
        "404":
          description: Transaction not found
        "500":
          description: Internal server error

    put:
      security:
        - Bearer: []
      tags:
        - transaction module
      summary: Update transaction details
      description: API to update transaction details
      parameters:
        - in: header
          name: Authorization
          description: Attach bearer JWT token
          required: true
          type: string
        - in: path
          name: idTransaction
          description: ID of the transaction to update
          required: true
          type: string
        - in: body
          name: body
          description: Updated transaction details
          required: true
          schema:
            $ref: "#/definitions/TransactionUpdate"
      produces:
        - application/json
      responses:
        "200":
          description: Transaction updated successfully
          schema:
            $ref: "#/definitions/transactionResponse"
        "400":
          description: Invalid input, missing fields, etc.
        "401":
          description: Unauthorized, invalid token, etc.
        "404":
          description: Transaction not found
        "500":
          description: Internal server error

    delete:
      security:
        - Bearer: []
      tags:
        - transaction module
      summary: Transaction delete API
      description: API for deleting a transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach bearer JWT token
          required: true
          type: string
        - in: path
          name: idTransaction
          description: ID of transaction to delete
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: Transaction deleted successfully
        "400":
          description: Invalid Fields
        "404":
          description: Transaction not found
        "500":
          description: Internal server error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

definitions:
  allTransactionsResponse:
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: array
        items:
          $ref: "#/definitions/transactionResponse"

  transactionResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        $ref: "#/definitions/transaction"

  transaction:
    type: object
    properties:
      id:
        type: string
        description: ID of the transaction
      date:
        type: string
        description: Date of the transaction
      amount:
        type: number
        description: Amount of the transaction
      description:
        type: string
        description: Description of the transaction
      category:
        type: string
        description: Category of the transaction
      notes:
        type: string
        description: Notes of the transaction

  TransactionUpdate:
    type: object
    properties:
      category:
        type: string
        description: New category for the transaction
      notes:
        type: string
        description: New notes for the transaction
